version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./config/Dockerfile.dev
    volumes:
      - ./src/:/app
      - /app/node_modules
    ports:
      - "80:80"
    stdin_open: true
